// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfqyiomyxqodezjucsmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmcXlpb215eHFvZGV6anVjc21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzQwMjIsImV4cCI6MjA3MTgxMDAyMn0.gWDWqJ-Bn_ixLuqX8oXUF3fCQqDooBj6enPw9KNvmrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});